name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-rtja2s6bb7v81lon.cn-chengdu.personal.cr.aliyuncs.com
        username: aliyun7864896671
        password: Yd@19911129
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://openmetadata/db:1.5.6 docker://crpi-rtja2s6bb7v81lon.cn-chengdu.personal.cr.aliyuncs.com/dilin/public:openmetadata-db-1.5.6
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
